export const SET_THUMBNAIL_STYLE = 'SET_THUMBNAIL_STYLE';
export const SET_FILMSTRIP_STYLE = 'SET_FILMSTRIP_STYLE';
export const SET_FILMSTRIP_HIDDEN = 'SET_FILMSTRIP_HIDDEN';
export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
