export const TOGGLE_ATHEER_BUFFER = 'TOGGLE_ATHEER_BUFFER';
export const TOGGLE_FLASHLIGHT_ON = 'TOGGLE_FLASHLIGHT_ON';
export const TOGGLE_FLASHLIGHT_OFF = 'TOGGLE_FLASHLIGHT_OFF';
export const CHECK_FLASHLIGHT_AVAILABILITY = 'CHECK_FLASHLIGHT_AVAILABILITY';
